//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.28 at 07:16:03 PM IST 
//


package com.batumbu.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Input complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Input">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tokenAuth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="corpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnRequestDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Input", propOrder = {
    "tokenAuth",
    "txnData",
    "serviceCode",
    "corpID",
    "requestID",
    "txnRequestDateTime"
})
public class Input {

    @XmlElement(required = true)
    protected String tokenAuth;
    @XmlElement(required = true)
    protected String txnData;
    @XmlElement(required = true)
    protected String serviceCode;
    @XmlElement(required = true)
    protected String corpID;
    @XmlElement(required = true)
    protected String requestID;
    @XmlElement(required = true)
    protected String txnRequestDateTime;

    /**
     * Gets the value of the tokenAuth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenAuth() {
        return tokenAuth;
    }

    /**
     * Sets the value of the tokenAuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenAuth(String value) {
        this.tokenAuth = value;
    }

    /**
     * Gets the value of the txnData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnData() {
        return txnData;
    }

    /**
     * Sets the value of the txnData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnData(String value) {
        this.txnData = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the corpID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorpID() {
        return corpID;
    }

    /**
     * Sets the value of the corpID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorpID(String value) {
        this.corpID = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the txnRequestDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnRequestDateTime() {
        return txnRequestDateTime;
    }

    /**
     * Sets the value of the txnRequestDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnRequestDateTime(String value) {
        this.txnRequestDateTime = value;
    }

}
