//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.28 at 07:19:16 PM IST 
//


package com.batumbu.model.module;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transferId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="debitAcctNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="benAcctNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="benName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="benBankName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="benBankAddr1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="benBankAddr2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="benBankAddr3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="benBankBranch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="benBankCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="benBankSWIFT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="memo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transferId",
    "txnDate",
    "debitAcctNo",
    "benAcctNo",
    "benName",
    "benBankName",
    "benBankAddr1",
    "benBankAddr2",
    "benBankAddr3",
    "benBankBranch",
    "benBankCode",
    "benBankSWIFT",
    "currCd",
    "amount",
    "memo"
})
@XmlRootElement(name = "transfer")
public class Transfer {

    @XmlElement(required = true)
    protected String transferId;
    @XmlElement(required = true)
    protected String txnDate;
    @XmlElement(required = true)
    protected String debitAcctNo;
    @XmlElement(required = true)
    protected String benAcctNo;
    @XmlElement(required = true)
    protected String benName;
    @XmlElement(required = true)
    protected String benBankName;
    @XmlElement(required = true)
    protected String benBankAddr1;
    @XmlElement(required = true)
    protected String benBankAddr2;
    @XmlElement(required = true)
    protected String benBankAddr3;
    @XmlElement(required = true)
    protected String benBankBranch;
    @XmlElement(required = true)
    protected String benBankCode;
    @XmlElement(required = true)
    protected String benBankSWIFT;
    @XmlElement(required = true)
    protected String currCd;
    @XmlElement(required = true)
    protected String amount;
    @XmlElement(required = true)
    protected String memo;

    /**
     * Gets the value of the transferId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferId() {
        return transferId;
    }

    /**
     * Sets the value of the transferId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferId(String value) {
        this.transferId = value;
    }

    /**
     * Gets the value of the txnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * Sets the value of the txnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnDate(String value) {
        this.txnDate = value;
    }

    /**
     * Gets the value of the debitAcctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitAcctNo() {
        return debitAcctNo;
    }

    /**
     * Sets the value of the debitAcctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitAcctNo(String value) {
        this.debitAcctNo = value;
    }

    /**
     * Gets the value of the benAcctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenAcctNo() {
        return benAcctNo;
    }

    /**
     * Sets the value of the benAcctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenAcctNo(String value) {
        this.benAcctNo = value;
    }

    /**
     * Gets the value of the benName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenName() {
        return benName;
    }

    /**
     * Sets the value of the benName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenName(String value) {
        this.benName = value;
    }

    /**
     * Gets the value of the benBankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenBankName() {
        return benBankName;
    }

    /**
     * Sets the value of the benBankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenBankName(String value) {
        this.benBankName = value;
    }

    /**
     * Gets the value of the benBankAddr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenBankAddr1() {
        return benBankAddr1;
    }

    /**
     * Sets the value of the benBankAddr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenBankAddr1(String value) {
        this.benBankAddr1 = value;
    }

    /**
     * Gets the value of the benBankAddr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenBankAddr2() {
        return benBankAddr2;
    }

    /**
     * Sets the value of the benBankAddr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenBankAddr2(String value) {
        this.benBankAddr2 = value;
    }

    /**
     * Gets the value of the benBankAddr3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenBankAddr3() {
        return benBankAddr3;
    }

    /**
     * Sets the value of the benBankAddr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenBankAddr3(String value) {
        this.benBankAddr3 = value;
    }

    /**
     * Gets the value of the benBankBranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenBankBranch() {
        return benBankBranch;
    }

    /**
     * Sets the value of the benBankBranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenBankBranch(String value) {
        this.benBankBranch = value;
    }

    /**
     * Gets the value of the benBankCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenBankCode() {
        return benBankCode;
    }

    /**
     * Sets the value of the benBankCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenBankCode(String value) {
        this.benBankCode = value;
    }

    /**
     * Gets the value of the benBankSWIFT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenBankSWIFT() {
        return benBankSWIFT;
    }

    /**
     * Sets the value of the benBankSWIFT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenBankSWIFT(String value) {
        this.benBankSWIFT = value;
    }

    /**
     * Gets the value of the currCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrCd() {
        return currCd;
    }

    /**
     * Sets the value of the currCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrCd(String value) {
        this.currCd = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemo() {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemo(String value) {
        this.memo = value;
    }

}
